[build-system]
requires = ["sip >=5", "PyQt-builder", "PyQt5"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "QHexEdit"
version = "0.8.9"

[tools.sip]
abi-version = "12.8"
project-factory = "pyqtbuild:PyQtProject"

[tool.sip.project]
sip-files-dir = "src"
